name: Publish .NET Project

on:
  push:
    tags:
      - 'v*'  # Triggers on tags starting with 'v' (e.g., v1.0.0)

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Generate manifest.json
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          REPO_DESCRIPTION="${{ github.event.repository.description }}"
          VERSION="${{ env.VERSION }}"
          # Remove 'ScheduleOne' from REPO_NAME
          REPO_NAME="${REPO_NAME//ScheduleOne/}"
          cat <<EOF > manifest.json
          {
            "name": "${REPO_NAME// /_}",
            "version_number": "${VERSION}",
            "website_url": "https://github.com/${{ github.repository }}",
            "description": "${REPO_DESCRIPTION}",
            "dependencies": [
              "LavaGang-MelonLoader-0.7.0"
            ]
          }
          EOF
        shell: bash

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'  # Adjust to your project's .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Publish
        run: dotnet publish --no-build --configuration Release --output ./publish

      - name: Prepare Thunderstore Package
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          VERSION="${{ env.VERSION }}"
          PACKAGE_NAME="${REPO_NAME//ScheduleOne/}"  # Remove 'ScheduleOne' from REPO_NAME
          echo "PACKAGE_NAME=${PACKAGE_NAME}" >> $GITHUB_ENV
          mkdir -p ThunderstorePackage/mods
          cp manifest.json ThunderstorePackage/
          cp README.md ThunderstorePackage/
          cp icon.png ThunderstorePackage/
          cp ./publish/${REPO_NAME}.dll ThunderstorePackage/
          cd ThunderstorePackage
          zip -r ${PACKAGE_NAME}-v${VERSION}.zip .
        shell: bash

      - name: Publish to Thunderstore
        uses: dhkatz/thunderstore-publish@v1.0.1
        with:
          token: ${{ secrets.TS_TOKEN }}
          communities: 'schedule-i'
          namespace: 'MaxtorCoder'
          name: 'SaveUtility'
          description: '${{ github.event.repository.description }}'
          version: '${{ env.VERSION }}'
          # path: '${{ env.PACKAGE_NAME }}_v${{ env.VERSION }}.zip'
          categories: mods
          deps: |
            "LavaGang-MelonLoader@0.7.0"

      - name: Output URL
        run: echo "Published Thunderstore package to ${{ steps.publish.outputs.url }}"
